#pragma once

#undef RGB_MATRIX_SLEEP
#undef RGB_MATRIX_DISABLE_WHEN_USB_SUSPENDED
#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#undef RGBLIGHT_DISABLE_WHEN_USB_SUSPENDED
#define SPLIT_TRANSACTION_IDS_USER RPC_SYNC_SLEEP, RGB_SYNC_TIME, REACTIVE_TAP_EVENT, COLOR_CHANGE
#define RGB_MATRIX_SPLIT { 42, 47 }